DTC_INCLUDE += $(srctree)/../sm8550-modules/qcom/opensource/audio-kernel/include

#remove useless qcom device tree in moto build
ifneq ($(CONFIG_MMI_DEVICE_DTBS),y)
ifeq ($(CONFIG_ARCH_KALAMA), y)
dtbo-y += kalama-audio.dtbo \
                 kalama-audio-cdp.dtbo \
                 kalama-audio-cdp-nfc.dtbo \
                 kalama-audio-wsa883x-cdp.dtbo \
                 kalama-audio-cdp-apq.dtbo \
                 kalama-audio-mtp.dtbo \
                 kalama-audio-mtp-nfc.dtbo \
                 kalama-audio-mtp-apq.dtbo \
                 kalama-audio-qrd.dtbo \
                 kalama-audio-atp.dtbo \
                 kalama-audio-rcm.dtbo \
                 kalama-audio-rumi.dtbo \
                 kalama-audio-hdk.dtbo \
                 kalama-sg-audio-hhg.dtbo
endif
else

dtbo-$(CONFIG_ARCH_KALAMA) += kalama-audio.dtbo
dtbo-$(CONFIG_RTWO_DTB) += kalama-audio-moto-rtwo-evb1.dtbo \
                           kalama-audio-moto-rtwo-dvt1b.dtbo

dtbo-$(CONFIG_OBERON_DTB) += kalama-audio-moto-oberon-evb.dtbo

dtbo-$(CONFIG_CTWO_DTB) += kalama-audio-moto-ctwo-evb.dtbo

dtbo-$(CONFIG_ARC_DTB) += kalama-audio-moto-arc-evb.dtbo

endif  #($(CONFIG_MMI_DEVICE_DTBS),y)

ifneq ($(CONFIG_MMI_DEVICE_DTBS),y)
ifeq ($(CONFIG_ARCH_KHAJE), y)
dtbo-y += khaje-audio.dtbo \
		khaje-audio-idp.dtbo \
		khaje-audio-qrd.dtbo \
		khaje-audio-qrd-hvdcp3p5.dtbo \
		khaje-audio-idp-nopmi.dtbo \
		khaje-audio-idp-90hz.dtbo \
                khajeg-audio-idp.dtbo \
                khajeg-audio-idp-90hz.dtbo \
		khajeg-audio-qrd.dtbo \
		khajeg-audio-qrd-hvdcp3p5.dtbo \
		khaje-audio-qrd-nopmi.dtbo \
		khajeg-audio-qrd-nopmi.dtbo \
		khaje-audio-atp.dtbo \
		khaje-audio-idp-pm8010.dtbo \
		khaje-audio-idp-usbc.dtbo \
		khaje-nowcd.dtbo
endif
else

dtbo-$(CONFIG_ARCH_KHAJE) += khaje-audio.dtbo
dtbo-$(CONFIG_RHODE_DTB) += khaje-audio-moto-rhode-evt.dtbo

dtbo-$(CONFIG_FOGONA_DTB) += khaje-audio-moto-fogona-evt.dtbo \
			     khaje-audio-moto-fogona-att.dtbo
endif  #($(CONFIG_MMI_DEVICE_DTBS),y)

ifeq ($(CONFIG_ARCH_SA8155), y)
dtbo-y +=  sa8155-audio.dtbo
endif

ifeq ($(CONFIG_ARCH_CROW), y)
#remove useless qcom device tree in moto build
ifneq ($(CONFIG_MMI_DEVICE_DTBS),y)
dtbo-y += crow-audio.dtbo \
                 crow-audio-idp.dtbo \
                 crow-audio-idp-wcd9395-aatc.dtbo \
                 crow-audio-idp-wcd9395-dmic.dtbo \
                 crow-audio-idp-wcd9395-wcd-dmic.dtbo \
                 crow-audio-qrd.dtbo \
                 crow-audio-atp.dtbo

else
dtbo-$(CONFIG_ARCH_CROW) += crow-audio.dtbo
dtbo-$(CONFIG_EQE_DTB) += crow-audio-moto-eqe-evb.dtbo
dtbo-$(CONFIG_EQE_DTB) += crow-audio-moto-eqe-evt.dtbo
endif  #($(CONFIG_MMI_DEVICE_DTBS),y)
endif

 always-y    := $(dtb-y) $(dtbo-y)
 subdir-y    := $(dts-dirs)
 clean-files    := *.dtb *.dtbo
