DTC_INCLUDE += $(srctree)/../sm8550-modules/qcom/opensource/camera-kernel

ifeq ($(CONFIG_ARCH_KALAMA), y)
include $(srctree)/$(src)/config/kalama.mk
endif

ifeq ($(CONFIG_ARCH_KHAJE), y)
include $(srctree)/$(src)/config/bengal.mk
endif

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
